In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/tang
!ls -l

/content/drive/MyDrive/tang
total 163076
-rw------- 1 root root    75612 Jul  1 08:36 gptang_v01_Base.ipynb
-rw------- 1 root root    76527 Jul  1 08:37 gptang_v02_SingleHead.ipynb
-rw------- 1 root root    77151 Jul  1 08:49 gptang_v03_MultiHead.ipynb
-rw------- 1 root root   121283 Jul  2 05:42 gptang_v04_FeedForward.ipynb
-rw------- 1 root root   101263 Jul  2 04:01 gptang_v05_Block.ipynb
-rw------- 1 root root   121962 Jul  2 03:41 gptang_v06_FeedForwardOpt.ipynb
-rw------- 1 root root   122414 Jul  2 03:20 gptang_v07_LayerNorm.ipynb
-rw------- 1 root root   122867 Jul  2 02:49 gptang_v08_Full.ipynb
-rw------- 1 root root 15120318 Jul  2 05:39 model_gptang_v04.pth
-rw------- 1 root root 17235670 Jul  2 03:56 model_gptang_v05.pth
-rw------- 1 root root 22754938 Jul  2 03:29 model_gptang_v06.pth
-rw------- 1 root root 22773710 Jul  2 03:13 model_gptang_v07.pth
-rw------- 1 root root 39400304 Jul  2 02:36 model_gptang_v08.pth
-rw------- 1 root root    91041 Jun 30 09:13 tang01_backup1

In [ ]:
text=""
with open("tang_clean.txt", "r") as f:
   tmp_text = f.read()
   text = text + tmp_text
f.close()

chars = sorted(list(set(text)))
print(len(chars))
print("".join(chars))

6848
□一丁七万丈三上下不与丐丑专且丕世丘丙业丛东丝丞两严丧个丫中丰丱串丳临丸丹为主丽举乂乃久么义之乌乍乎乏乐乔乖乘乙九乞也习乡书买乱乳乾了予争事二于亏云互五井亘亚些亟亡亢交亥亦产亨亩享京亭亮亲亳亵亸亹人亿什仁仄仅仆仇今介仍从仑仓仔仕他仗付仙仝仞仡代令以仪仰仲仳价任仿企伉伊伋伍伎伏伐休众优会伛伞伟传伤伥伦伧伪伫伯估伴伶伸伺似伽但佉位低住佐佑体何佗余佚佛作佝佞你佣佥佩佪佯佳佶佺佾使侁侃侄侈例侍侏侑侔侗侘供依侠侣侥侧侨侪侬侮侯侵侹便促俄俊俋俎俗俘俚俛俜保俞俟信俣俦俨俩俪俫俭修俯俱俳俶俸俾倅倍倏倒倔倕倖倘候倚倜借倡倥倦倨倩倪倬倭倰债值倾偃假偈偎偏偓偕停健偪偬偲偶偷偻偾偿傀傅傍傥储傩催傭傲傺僁僇僎像僖僚僜僦僧僬僭僮僰僴僵僻僾儆儋儒儓儗儡儭儽儿兀允元兄充兆先光克免兑兔兕兖党兜兟兢入全八公六兮兰共关兴兵其具典兹养兼兽冀冁内冈冉册再冏冒冕冗写军农冠冢冤冥冬冯冰冱冲决况冶冷冻冽净凄准凉凊凋凌减凑凘凚凛凝几凡凤凫凭凯凰凶凸凹出击函凿刀刁刃分切刈刊刍刎刑划刓刖列刘则刚创刜初删判利别刬刮到刲刳制刷券刹刺刻刿剂剃剉削剌前剑剔剖剜剞剡剥剧剩剪副割剸剽剿劂劈劖劘劚力劝办功加务劣动助努劫劬劭励劲劳劻劼劾势勃勇勉勋勍勒勖勘募勤勩勷勺勾勿匀匄包匆匈匌匍匏匐匕化北匙匝匠匡匣匦匪匮匹区医匼匿十千升午卉半华协卑卒卓单卖南博卜卞占卢卤卦卧卨卫卮卯印危即却卵卷卸卺卼卿厄厅历厉压厌厓厕厖厘厚厝原厢厥厦厨厩厮去县参叆叇又叉及友双反发叔取受变叙叛叟叠口古句叨叩只叫召叮可台叱史右叵叶号司叹吁吃各合吉吊同名后吏吐向吒吓吕君吝吞吟吠否含听吭吮启吰吴吷吸吹吺吻吼吾呀呃呆呈告呐呕呗员呙呜呦周呱味呴呵呶呷呻呼命咀咂咄咆咋和咍咎咏咒咙咚咛咡咢咤咥咨咩咫咬咳咷咸咻咽咿哀品哂哄哆哇哈哉响哑哓哕哗哙哜哢哤哥哦哭哮哲哳哺哽唁唅唇唏唐唝唠唤唧售唯唱唳唶唼唽唾啀啁啄啅商啐啑啖啜啧啬啭啮啴啸啻啼啾喁喂喃善喈喉喋喍喎喑喓喔喘喙喜喝喟喢喣喧喷喻喽嗄嗅嗈嗒嗔嗗嗛嗜嗟嗢嗣嗤嗥嗫嗷嗽嗾嘈嘉嘐嘒嘕嘘嘤嘬嘱嘲嘴嘶嘹嘻嘿噀噅噆噇噌噎噏噞噢噣噤器噩噪噫噬噭噰噱嚄嚅嚏嚗嚘嚚嚣嚬嚭嚱嚼囊囐囗囚四回因团园困围囷囹固国图囿圃圄圆圈圉圜圞土圠圣在圭圮圯地圹场圻圿址坂均坊坌坎坏坐坑块坚坛坞坟坠坡坤坦坩坫坯坰坱坲坳坷坻坼垂垄垆型垌垒垓垛垞垠垡垢垣垤垦垩垫垲埂埃埆埇埋城埏埒埘埙埞域埤埭埳埴培基埽堂堄堆堇堌堑堕堙堛堞堠堡堤堪堮堰堵塉塌塍塔塘塞塠填塸塿墀墁境墅墉墍墐墓墙墝增墟

In [ ]:
vocab_size = len(chars)
# 直接给编码映射关系
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
# 建立编码和解码函数
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: "".join([itos[i] for i in l])

In [ ]:
encode("我是你好一二三四五六七八九十")

[1852, 2255, 177, 1065, 1, 70, 6, 859, 75, 340, 3, 338, 56, 532]

In [ ]:
decode([1852, 2255, 177, 1065, 1, 70, 6, 859, 75, 340, 3, 338, 56, 532])

'我是你好一二三四五六七八九十'

In [1]:
import torch
#device="cuda" if torch.cuda.is_available() else "cpu"
device="cpu"
if torch.cuda.is_available():
    device="cuda"
if torch.backends.mps.is_available():
    device="mps"
print(device)

mps


In [ ]:
import torch
data=torch.tensor(encode(text),dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])


torch.Size([1449490]) torch.int64
tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011, 3655, 1296, 4317, 2727,
         533, 1266, 5557, 3910, 1231, 3651, 6257, 6458, 5773, 4976, 5841, 2035,
        2774, 6420, 5267, 5777,  389, 5013,   73, 2219, 6233, 1294, 6178, 6408,
        3217,  406, 4317, 3578, 1338, 1532, 4400, 2355,  477, 1363, 2172, 4490,
        6508, 5725, 3409,  523,  651, 6838,  870, 5985, 4320, 1925,  398, 4103,
        6353, 4349, 2193,  108, 4316, 4364, 1458, 4643, 5768,  563, 1264, 2698,
          42, 2988, 3560, 2681, 2493, 5267,  904,  349, 3936, 2699,  406, 5359,
        2404,  272, 4638, 2673, 2700, 1234, 6264, 1556,  365, 2240, 2331, 6524,
        6495, 3579, 2904, 3548, 1752, 6252, 4875, 5013, 1566,  768, 3394, 1743,
        1677, 4097, 6161, 5529, 5371, 1026, 4420,   71,  350,   42, 1640,  255,
        6691, 4044,   34,   51, 6460, 3722,  648, 2672, 4706, 4685, 1677, 4090,
        6360, 2352, 1566, 2992, 2691,  395, 3650, 6269, 1591,  398, 4500, 2378,
      

In [ ]:
n=(int)(len(data)*0.09)*10
train_data=data[0:n]
val_data=data[n:]
print(len(train_data), len(val_data))

1304540 144950


In [ ]:
block_size=9
train_data[:block_size+1]

tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011, 3655, 1296])

In [ ]:
x=train_data[:block_size]
y=train_data[1:block_size+1]
for t in range(block_size):
  context=x[:t+1]
  target=y[t]
  print(f"when input {context} then answer is {target}")

when input tensor([3926]) then answer is 1424
when input tensor([3926, 1424]) then answer is 6253
when input tensor([3926, 1424, 6253]) then answer is 1462
when input tensor([3926, 1424, 6253, 1462]) then answer is 1206
when input tensor([3926, 1424, 6253, 1462, 1206]) then answer is 408
when input tensor([3926, 1424, 6253, 1462, 1206,  408]) then answer is 5451
when input tensor([3926, 1424, 6253, 1462, 1206,  408, 5451]) then answer is 1011
when input tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011]) then answer is 3655
when input tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011, 3655]) then answer is 1296


In [ ]:
torch.manual_seed(1337)
batch_size=32
block_size=9

def get_batch(split):
  data=train_data if split=="train" else val_data
  #find the start position
  ix=torch.randint((int)(len(data)/10-1),(batch_size,))*10
  #for t in ix:
    #print(t)
  x=torch.stack([data[i:i+block_size] for i in ix])
  y=torch.stack([data[i+1:i+block_size+1] for i in ix])
  x=x.to(device)
  y=y.to(device)
  return x, y


In [ ]:
xb,yb=get_batch("train")
print("Inputs:")
print(xb.shape)
print(xb)
print("Outputs:")
print(yb.shape)
print(yb)
print("--------------")

for b in range(batch_size):
  for t in range(block_size):
    context=xb[b, :t+1]
    target=yb[b,t]
    print(f"when input is {context.tolist()}, the target is {target}")

Inputs:
torch.Size([32, 9])
tensor([[2195, 5368, 3676, 5835, 5602, 2992, 6360,  159, 2167],
        [ 213,  213, 1652, 5835, 5602,  859, 2143,    9, 1471],
        [2219, 2305, 6776,   73,  629, 1491, 2985, 3650, 6544],
        [2658, 3307, 6420, 4705,  336, 1532, 1868, 3141, 2767],
        [3975, 4292, 2490, 4705,  903,    9, 5266, 3926, 2228],
        [5985, 4320,  324, 3556, 5835, 3409, 2430,  560, 5412],
        [2340, 5602, 2711, 2346, 3972, 1974, 2342,  106, 1436],
        [1314, 2829, 5557, 3692,  451, 3732, 3712, 2702, 5602],
        [1798,  641,  919, 5978, 2094,    9,  187, 4875, 6408],
        [5788, 2842, 3578, 3781, 4003, 2712, 6267,  598, 2559],
        [ 660,  641, 2196, 1646, 5752,  413, 6159, 5519, 1029],
        [ 612, 1509, 1235, 2523, 5980, 5368,  345, 1305, 2786],
        [1499, 1524, 1673, 6269,  383, 2985, 1299,  784, 3193],
        [ 117, 1272, 5556, 1236, 3409, 4738, 6408,  389,  859],
        [2774, 3441, 3560, 5835,  675, 2785, 3505, 5766, 3709],
        [ 12

In [ ]:
xb,yb=get_batch("val")
print("Inputs:")
print(xb.shape)
print(xb)
print("Outputs:")
print(yb.shape)
print(yb)
print("--------------")

for b in range(batch_size):
  for t in range(block_size):
    context=xb[b, :t+1]
    target=yb[b,t]
    print(f"when input is {context.tolist()}, the target is {target}")

Inputs:
torch.Size([32, 9])
tensor([[6269, 4557, 6710, 6113, 5980, 3463, 2468,  398, 2589],
        [5902, 4351, 1630,  159, 2767, 2150,  123, 6037,   37],
        [3239, 5400, 4013, 1066,  169, 5398,  209, 5266, 5981],
        [  73, 6277,  647,   36, 2284, 2496, 6773, 5265, 4283],
        [3910, 1707,  429, 5814, 4685, 5494, 1296,  612,  784],
        [3459, 2378, 6152,  439,  836,  128, 5165, 4543, 5773],
        [1020, 3923, 2196,  390, 6421, 3918, 2219, 2323, 6152],
        [  63, 1359, 2785,    7, 4681, 4426, 1276,  594, 3918],
        [1268, 5927,  106, 2341, 5770, 2217, 6313,  406,   16],
        [3544, 1037, 2332, 6753, 5789, 3545, 1291, 4879, 2219],
        [1194, 3993, 3214, 1597, 1624,  169,   69, 6194,  644],
        [5927,   91, 3560,  587, 5789,  653,  892, 5326,  821],
        [2250, 6267, 2217, 6560,    8, 4705, 2408, 2332, 3778],
        [   1,   40, 2904, 6294, 2888,  533, 1491,  882,  214],
        [1024, 4730, 1489, 4987, 2172,   29, 2332, 2300, 2930],
        [149

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

class Head(nn.Module):
  def __init__(self, head_size):
    super().__init__()
    self.key=nn.Linear(n_embed, head_size, bias=False)
    self.query=nn.Linear(n_embed, head_size, bias=False)
    self.value=nn.Linear(n_embed, head_size, bias=False)
    #print(torch.tril(torch.ones(block_size, block_size)))
    self.register_buffer('tril',torch.tril(torch.ones(block_size, block_size)))
    #self.tril=torch.tril(torch.ones(block_size, block_size))

  def forward(self,x):
    B,T,C=x.shape
    k=self.key(x)
    q=self.query(x)
    wei=q@k.transpose(-2,-1)*C**-0.5
    wei=wei.masked_fill(self.tril[:T,:T]==0,float("-inf"))
    wei=F.softmax(wei,dim=-1)

    v=self.value(x)
    out=wei@v
    return out


In [ ]:
class MultiHeadAttention(nn.Module):
  def __init__(self, num_heads, head_size):
    super().__init__()
    self.heads=nn.ModuleList([Head(head_size) for _ in range(num_heads)])

  def forward(self, x):
    return torch.cat([h(x) for h in self.heads], dim=-1)

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)
n_embed=256

class BigramLanguageModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.token_embedding_table=nn.Embedding(vocab_size, n_embed)
    self.postion_embedding_table=nn.Embedding(block_size,n_embed)
    #self.sa_head=Head(n_embed)
    self.sa_heads=MultiHeadAttention(4, n_embed//4)
    self.lm_head=nn.Linear(n_embed,vocab_size)

  def forward(self, idx, targets=None):
    B,T=idx.shape
    tok_emb=self.token_embedding_table(idx)
    pos_emd=self.postion_embedding_table(torch.arange(T,device=device))
    x=tok_emb+pos_emd
    #x=self.sa_head(x)
    x=self.sa_heads(x)
    logits=self.lm_head(x)
    if targets is None:
      loss=None
    else:
      B,T,C=logits.shape
      logits=logits.view(B*T,C)
      targets=targets.view(B*T)
      loss=F.cross_entropy(logits, targets)
      #print(loss)
    return logits, loss

  def generate(self, idx, max_new_tokens):
    for _ in range(max_new_tokens):
      idx_cond=idx[:,-block_size:]
      logits,loss=self(idx_cond)
      logits=logits[:,-1,:]
      probs=F.softmax(logits, dim=-1)
      idx_next=torch.multinomial(probs, num_samples=1)
      idx=torch.cat((idx, idx_next),dim=1)
    return idx

model=BigramLanguageModel()
m=model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
logits, loss =m(xb,yb)
print(logits.shape)
print(loss)
print(decode(m.generate(torch.ones((1,1),dtype=torch.long,device=device), max_new_tokens=9)[0].tolist()))

3.711936 M parameters
torch.Size([288, 6848])
tensor(8.8632, grad_fn=<NllLossBackward0>)
一匈请歜霜查璨歌瑚怳


In [ ]:
optimizer=torch.optim.AdamW(m.parameters(),lr=1e-3)

In [ ]:
batch_size=32
for steps in range(1000):
  xb, yb = get_batch("train")
  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

  print(steps, loss.item())

0 5.91839599609375
1 5.991588115692139
2 5.803215503692627
3 5.895026683807373
4 5.878892421722412
5 5.832464694976807
6 5.933473587036133
7 5.902184963226318
8 5.775406360626221
9 6.162847518920898
10 5.809173107147217
11 6.2435197830200195
12 6.014225006103516
13 6.069600582122803
14 6.1885986328125
15 5.858610153198242
16 6.042688369750977
17 5.563008785247803
18 5.932313919067383
19 5.818160057067871
20 5.851694107055664
21 5.862136363983154
22 5.833768844604492
23 5.8886189460754395
24 5.8314995765686035
25 6.118167877197266
26 5.875767230987549
27 6.173543930053711
28 5.656064510345459
29 6.067094802856445
30 6.121617317199707
31 5.962953567504883
32 6.059366226196289
33 6.052263259887695
34 6.002975940704346
35 6.297226428985596
36 6.664297103881836
37 5.989932537078857
38 5.953291416168213
39 5.760122776031494
40 5.922659397125244
41 6.240253925323486
42 6.085092544555664
43 6.010940074920654
44 6.115950107574463
45 5.881209850311279
46 5.623559951782227
47 5.934724807739258
48

In [ ]:
eval_iter=32

@torch.no_grad()
def estimate_loss():
  out={}
  model.eval()
  for split in ["train", "val"]:
    losses=torch.zeros(eval_iter)
    for k in range(eval_iter):
      X, Y = get_batch(split)
      logits, loss=model(X,Y)
      losses[k]=loss.item()
    out[split]=losses.mean()
  model.train()
  return out




In [ ]:
estimate_loss()

{'train': tensor(5.7361), 'val': tensor(6.3216)}

In [ ]:
for _ in range(30):
  myen=encode("白")
  mylen=len(myen)
  myword=torch.tensor(myen,dtype=torch.long, device=device)
  myword=torch.reshape(myword, (1,-1))
  mysen=decode(m.generate(myword, max_new_tokens=10-mylen)[0].tolist())
  print(mysen[:5]+"，"+mysen[5:]+"。")

白衫鼙鼓互，落夜更头关。
白头增羽辇，蜗食映元刘。
白云下酒子，星救恣山困。
白草坚祖月，明月沉中云。
白霓寤宝航，青秋动山晓。
白云分卷夕，相背惜诗尘。
白马尘嚣碗，青槐钓旆安。
白云收藤枝，清袖满长桥。
白犬李陵逸，黄牛归麦棋。
白黑俱避述，出入溪上身。
白云吟遥自，红发近岚仙。
白发江龙气，红毫渭城苦。
白云收屏趣，樽浅引啼秋。
白发何时步，慰尔自素器。
白首日萧条，年行卒相许。
白首刀瘢珊，按唱奏块归。
白帝一何赖，青山泛周享。
白波无鸟水，黄汉鬓鸣琴。
白云登一望，新浦共休经。
白刃别流长，赤浦下门门。
白玉遗灵落，青鸾羽檄瑶。
白须溅袖罅，涧色袭芳新。
白首荆山近，黄钟予寺僧。
白日全相送，青春半处愁。
白云昏警吹，百啭不自冰。
白雨气浮清，双栖永康庄。
白日短衣湿，青春争发硎。
白玉红霞发，丹珠凤沙斑。
白璧新妆影，棠踪一濯车。
白日各有归，新敲永获迟。


In [ ]:
torch.save(model.state_dict(), "model_gptang_v03.pth")

In [ ]:
# 加载保存的参数c
model = BigramLanguageModel()
m = model.to(device)
# 加载已保存的参数
m.load_state_dict(torch.load("model_gptang_v03.pth", weights_only=True))