In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/tang
!ls -l

/content/drive/MyDrive/tang
total 86866
-rw------- 1 root root    75612 Jul  1 08:36 gptang_v01_Base.ipynb
-rw------- 1 root root    76527 Jul  1 08:37 gptang_v02_SingleHead.ipynb
-rw------- 1 root root    77151 Jul  1 08:49 gptang_v03_MultiHead.ipynb
-rw------- 1 root root    77774 Jul  1 09:01 gptang_v04_FeedForward.ipynb
-rw------- 1 root root    78600 Jul  1 09:20 gptang_v05_Block.ipynb
-rw------- 1 root root    77785 Jul  1 09:29 gptang_v06_FeedForwardOpt.ipynb
-rw------- 1 root root    78953 Jul  1 09:40 gptang_v07_LayerNorm.ipynb
-rw------- 1 root root   122867 Jul  2 02:49 gptang_v08_Full.ipynb
-rw------- 1 root root 39400304 Jul  2 02:36 model_gptang_v08.pth
-rw------- 1 root root    91041 Jun 30 09:13 tang01_backup1.ipynb
-rw------- 1 root root   100650 Jun 30 09:13 tang01_backup2.ipynb
-rw------- 1 root root    91297 Jul  1 02:55 tang01_backup3.ipynb
-rw------- 1 root root    91856 Jul  1 03:41 tang01_backup5.ipynb
-rw------- 1 root root    92415 Jul  1 06:07 tang01_backup6.

In [1]:
text=""
with open("tang_clean.txt", "r") as f:
   tmp_text = f.read()
   text = text + tmp_text
f.close()

chars = sorted(list(set(text)))
print(len(chars))
print("".join(chars))

6848
□一丁七万丈三上下不与丐丑专且丕世丘丙业丛东丝丞两严丧个丫中丰丱串丳临丸丹为主丽举乂乃久么义之乌乍乎乏乐乔乖乘乙九乞也习乡书买乱乳乾了予争事二于亏云互五井亘亚些亟亡亢交亥亦产亨亩享京亭亮亲亳亵亸亹人亿什仁仄仅仆仇今介仍从仑仓仔仕他仗付仙仝仞仡代令以仪仰仲仳价任仿企伉伊伋伍伎伏伐休众优会伛伞伟传伤伥伦伧伪伫伯估伴伶伸伺似伽但佉位低住佐佑体何佗余佚佛作佝佞你佣佥佩佪佯佳佶佺佾使侁侃侄侈例侍侏侑侔侗侘供依侠侣侥侧侨侪侬侮侯侵侹便促俄俊俋俎俗俘俚俛俜保俞俟信俣俦俨俩俪俫俭修俯俱俳俶俸俾倅倍倏倒倔倕倖倘候倚倜借倡倥倦倨倩倪倬倭倰债值倾偃假偈偎偏偓偕停健偪偬偲偶偷偻偾偿傀傅傍傥储傩催傭傲傺僁僇僎像僖僚僜僦僧僬僭僮僰僴僵僻僾儆儋儒儓儗儡儭儽儿兀允元兄充兆先光克免兑兔兕兖党兜兟兢入全八公六兮兰共关兴兵其具典兹养兼兽冀冁内冈冉册再冏冒冕冗写军农冠冢冤冥冬冯冰冱冲决况冶冷冻冽净凄准凉凊凋凌减凑凘凚凛凝几凡凤凫凭凯凰凶凸凹出击函凿刀刁刃分切刈刊刍刎刑划刓刖列刘则刚创刜初删判利别刬刮到刲刳制刷券刹刺刻刿剂剃剉削剌前剑剔剖剜剞剡剥剧剩剪副割剸剽剿劂劈劖劘劚力劝办功加务劣动助努劫劬劭励劲劳劻劼劾势勃勇勉勋勍勒勖勘募勤勩勷勺勾勿匀匄包匆匈匌匍匏匐匕化北匙匝匠匡匣匦匪匮匹区医匼匿十千升午卉半华协卑卒卓单卖南博卜卞占卢卤卦卧卨卫卮卯印危即却卵卷卸卺卼卿厄厅历厉压厌厓厕厖厘厚厝原厢厥厦厨厩厮去县参叆叇又叉及友双反发叔取受变叙叛叟叠口古句叨叩只叫召叮可台叱史右叵叶号司叹吁吃各合吉吊同名后吏吐向吒吓吕君吝吞吟吠否含听吭吮启吰吴吷吸吹吺吻吼吾呀呃呆呈告呐呕呗员呙呜呦周呱味呴呵呶呷呻呼命咀咂咄咆咋和咍咎咏咒咙咚咛咡咢咤咥咨咩咫咬咳咷咸咻咽咿哀品哂哄哆哇哈哉响哑哓哕哗哙哜哢哤哥哦哭哮哲哳哺哽唁唅唇唏唐唝唠唤唧售唯唱唳唶唼唽唾啀啁啄啅商啐啑啖啜啧啬啭啮啴啸啻啼啾喁喂喃善喈喉喋喍喎喑喓喔喘喙喜喝喟喢喣喧喷喻喽嗄嗅嗈嗒嗔嗗嗛嗜嗟嗢嗣嗤嗥嗫嗷嗽嗾嘈嘉嘐嘒嘕嘘嘤嘬嘱嘲嘴嘶嘹嘻嘿噀噅噆噇噌噎噏噞噢噣噤器噩噪噫噬噭噰噱嚄嚅嚏嚗嚘嚚嚣嚬嚭嚱嚼囊囐囗囚四回因团园困围囷囹固国图囿圃圄圆圈圉圜圞土圠圣在圭圮圯地圹场圻圿址坂均坊坌坎坏坐坑块坚坛坞坟坠坡坤坦坩坫坯坰坱坲坳坷坻坼垂垄垆型垌垒垓垛垞垠垡垢垣垤垦垩垫垲埂埃埆埇埋城埏埒埘埙埞域埤埭埳埴培基埽堂堄堆堇堌堑堕堙堛堞堠堡堤堪堮堰堵塉塌塍塔塘塞塠填塸塿墀墁境墅墉墍墐墓墙墝增墟

In [2]:
vocab_size = len(chars)
# 直接给编码映射关系
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
# 建立编码和解码函数
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: "".join([itos[i] for i in l])

In [3]:
encode("我是你好一二三四五六七八九十")

[1852, 2255, 177, 1065, 1, 70, 6, 859, 75, 340, 3, 338, 56, 532]

In [4]:
decode([1852, 2255, 177, 1065, 1, 70, 6, 859, 75, 340, 3, 338, 56, 532])

'我是你好一二三四五六七八九十'

In [5]:
import torch
#device="cuda" if torch.cuda.is_available() else "cpu"
device="cpu"
if torch.cuda.is_available():
    device="cuda"
if torch.backends.mps.is_available():
    device="mps"
print(device)

mps


In [6]:
import torch
data=torch.tensor(encode(text),dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])


torch.Size([1449490]) torch.int64
tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011, 3655, 1296, 4317, 2727,
         533, 1266, 5557, 3910, 1231, 3651, 6257, 6458, 5773, 4976, 5841, 2035,
        2774, 6420, 5267, 5777,  389, 5013,   73, 2219, 6233, 1294, 6178, 6408,
        3217,  406, 4317, 3578, 1338, 1532, 4400, 2355,  477, 1363, 2172, 4490,
        6508, 5725, 3409,  523,  651, 6838,  870, 5985, 4320, 1925,  398, 4103,
        6353, 4349, 2193,  108, 4316, 4364, 1458, 4643, 5768,  563, 1264, 2698,
          42, 2988, 3560, 2681, 2493, 5267,  904,  349, 3936, 2699,  406, 5359,
        2404,  272, 4638, 2673, 2700, 1234, 6264, 1556,  365, 2240, 2331, 6524,
        6495, 3579, 2904, 3548, 1752, 6252, 4875, 5013, 1566,  768, 3394, 1743,
        1677, 4097, 6161, 5529, 5371, 1026, 4420,   71,  350,   42, 1640,  255,
        6691, 4044,   34,   51, 6460, 3722,  648, 2672, 4706, 4685, 1677, 4090,
        6360, 2352, 1566, 2992, 2691,  395, 3650, 6269, 1591,  398, 4500, 2378,
      

In [7]:
n=(int)(len(data)*0.09)*10
train_data=data[0:n]
val_data=data[n:]
print(len(train_data), len(val_data))

1304540 144950


In [8]:
block_size=9
train_data[:block_size+1]

tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011, 3655, 1296])

In [9]:
x=train_data[:block_size]
y=train_data[1:block_size+1]
for t in range(block_size):
  context=x[:t+1]
  target=y[t]
  print(f"when input {context} then answer is {target}")

when input tensor([3926]) then answer is 1424
when input tensor([3926, 1424]) then answer is 6253
when input tensor([3926, 1424, 6253]) then answer is 1462
when input tensor([3926, 1424, 6253, 1462]) then answer is 1206
when input tensor([3926, 1424, 6253, 1462, 1206]) then answer is 408
when input tensor([3926, 1424, 6253, 1462, 1206,  408]) then answer is 5451
when input tensor([3926, 1424, 6253, 1462, 1206,  408, 5451]) then answer is 1011
when input tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011]) then answer is 3655
when input tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011, 3655]) then answer is 1296


In [10]:
torch.manual_seed(1337)
batch_size=32
block_size=9

def get_batch(split):
  data=train_data if split=="train" else val_data
  #find the start position
  ix=torch.randint((int)(len(data)/10-1),(batch_size,))*10
  #for t in ix:
    #print(t)
  x=torch.stack([data[i:i+block_size] for i in ix])
  y=torch.stack([data[i+1:i+block_size+1] for i in ix])
  x=x.to(device)
  y=y.to(device)
  return x, y


In [11]:
xb,yb=get_batch("train")
print("Inputs:")
print(xb.shape)
print(xb)
print("Outputs:")
print(yb.shape)
print(yb)
print("--------------")

for b in range(batch_size):
  for t in range(block_size):
    context=xb[b, :t+1]
    target=yb[b,t]
    print(f"when input is {context.tolist()}, the target is {target}")

Inputs:
torch.Size([32, 9])
tensor([[2195, 5368, 3676, 5835, 5602, 2992, 6360,  159, 2167],
        [ 213,  213, 1652, 5835, 5602,  859, 2143,    9, 1471],
        [2219, 2305, 6776,   73,  629, 1491, 2985, 3650, 6544],
        [2658, 3307, 6420, 4705,  336, 1532, 1868, 3141, 2767],
        [3975, 4292, 2490, 4705,  903,    9, 5266, 3926, 2228],
        [5985, 4320,  324, 3556, 5835, 3409, 2430,  560, 5412],
        [2340, 5602, 2711, 2346, 3972, 1974, 2342,  106, 1436],
        [1314, 2829, 5557, 3692,  451, 3732, 3712, 2702, 5602],
        [1798,  641,  919, 5978, 2094,    9,  187, 4875, 6408],
        [5788, 2842, 3578, 3781, 4003, 2712, 6267,  598, 2559],
        [ 660,  641, 2196, 1646, 5752,  413, 6159, 5519, 1029],
        [ 612, 1509, 1235, 2523, 5980, 5368,  345, 1305, 2786],
        [1499, 1524, 1673, 6269,  383, 2985, 1299,  784, 3193],
        [ 117, 1272, 5556, 1236, 3409, 4738, 6408,  389,  859],
        [2774, 3441, 3560, 5835,  675, 2785, 3505, 5766, 3709],
        [ 12

In [12]:
xb,yb=get_batch("val")
print("Inputs:")
print(xb.shape)
print(xb)
print("Outputs:")
print(yb.shape)
print(yb)
print("--------------")

for b in range(batch_size):
  for t in range(block_size):
    context=xb[b, :t+1]
    target=yb[b,t]
    print(f"when input is {context.tolist()}, the target is {target}")

Inputs:
torch.Size([32, 9])
tensor([[6269, 4557, 6710, 6113, 5980, 3463, 2468,  398, 2589],
        [5902, 4351, 1630,  159, 2767, 2150,  123, 6037,   37],
        [3239, 5400, 4013, 1066,  169, 5398,  209, 5266, 5981],
        [  73, 6277,  647,   36, 2284, 2496, 6773, 5265, 4283],
        [3910, 1707,  429, 5814, 4685, 5494, 1296,  612,  784],
        [3459, 2378, 6152,  439,  836,  128, 5165, 4543, 5773],
        [1020, 3923, 2196,  390, 6421, 3918, 2219, 2323, 6152],
        [  63, 1359, 2785,    7, 4681, 4426, 1276,  594, 3918],
        [1268, 5927,  106, 2341, 5770, 2217, 6313,  406,   16],
        [3544, 1037, 2332, 6753, 5789, 3545, 1291, 4879, 2219],
        [1194, 3993, 3214, 1597, 1624,  169,   69, 6194,  644],
        [5927,   91, 3560,  587, 5789,  653,  892, 5326,  821],
        [2250, 6267, 2217, 6560,    8, 4705, 2408, 2332, 3778],
        [   1,   40, 2904, 6294, 2888,  533, 1491,  882,  214],
        [1024, 4730, 1489, 4987, 2172,   29, 2332, 2300, 2930],
        [149

In [13]:
import torch
import torch.nn as nn
from torch.nn import functional as F

class Head(nn.Module):
  def __init__(self, head_size):
    super().__init__()
    self.key=nn.Linear(n_embed, head_size, bias=False)
    self.query=nn.Linear(n_embed, head_size, bias=False)
    self.value=nn.Linear(n_embed, head_size, bias=False)
    #print(torch.tril(torch.ones(block_size, block_size)))
    self.register_buffer('tril',torch.tril(torch.ones(block_size, block_size)))
    #self.tril=torch.tril(torch.ones(block_size, block_size))

  def forward(self,x):
    B,T,C=x.shape
    k=self.key(x)
    q=self.query(x)
    wei=q@k.transpose(-2,-1)*C**-0.5
    wei=wei.masked_fill(self.tril[:T,:T]==0,float("-inf"))
    wei=F.softmax(wei,dim=-1)

    v=self.value(x)
    out=wei@v
    return out


In [14]:
class MultiHeadAttention(nn.Module):
  def __init__(self, num_heads, head_size):
    super().__init__()
    self.heads=nn.ModuleList([Head(head_size) for _ in range(num_heads)])

  def forward(self, x):
    return torch.cat([h(x) for h in self.heads], dim=-1)

In [15]:
class FeedForward(nn.Module):
  def __init__(self, n_embed):
    super().__init__()
    self.net=nn.Sequential(
        nn.Linear(n_embed, n_embed*4),
        nn.ReLU(),
        nn.Linear(n_embed*4, n_embed),
    )

  def forward(self, x):
    return self.net(x)

In [16]:
class Block(nn.Module):
  def __init__ (self, n_embed, n_head):
    super().__init__()
    head_size=n_embed//n_head
    self.sa=MultiHeadAttention(n_head,head_size)
    self.ffwd=FeedForward(n_embed)
    self.ln1=nn.LayerNorm(n_embed)
    self.ln2=nn.LayerNorm(n_embed)

  def forward(self, x):
    x=x+self.sa(self.ln1(x))
    x=x+self.ffwd(self.ln2(x))
    return x

In [17]:
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)
n_embed=256

class BigramLanguageModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.token_embedding_table=nn.Embedding(vocab_size, n_embed)
    self.postion_embedding_table=nn.Embedding(block_size,n_embed)
    #self.sa_head=Head(n_embed)
    #self.sa_heads=MultiHeadAttention(4, n_embed//4)
    #self.ffwd=FeedForward(n_embed)

    self.blocks=nn.Sequential(
        Block(n_embed, n_head=4),
        Block(n_embed, n_head=4),
        Block(n_embed, n_head=4),
        nn.LayerNorm(n_embed),
    )
    self.lm_head=nn.Linear(n_embed,vocab_size)

  def forward(self, idx, targets=None):
    B,T=idx.shape
    tok_emb=self.token_embedding_table(idx)
    pos_emd=self.postion_embedding_table(torch.arange(T,device=device))
    x=tok_emb+pos_emd
    #x=self.sa_head(x)
    #x=self.sa_heads(x)
    #x=self.ffwd(x)
    x=self.blocks(x)
    logits=self.lm_head(x)
    if targets is None:
      loss=None
    else:
      B,T,C=logits.shape
      logits=logits.view(B*T,C)
      targets=targets.view(B*T)
      loss=F.cross_entropy(logits, targets)
      #print(loss)
    return logits, loss

  def generate(self, idx, max_new_tokens):
    for _ in range(max_new_tokens):
      idx_cond=idx[:,-block_size:]
      logits,loss=self(idx_cond)
      logits=logits[:,-1,:]
      probs=F.softmax(logits, dim=-1)
      idx_next=torch.multinomial(probs, num_samples=1)
      idx=torch.cat((idx, idx_next),dim=1)
    return idx

model=BigramLanguageModel()
m=model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
logits, loss =m(xb,yb)
print(logits.shape)
print(loss)
print(decode(m.generate(torch.ones((1,1),dtype=torch.long,device=device), max_new_tokens=9)[0].tolist()))

5.68544 M parameters
torch.Size([288, 6848])
tensor(9.0212, device='mps:0', grad_fn=<NllLossBackward0>)
一索巷抗祇情高癞棁呙


In [18]:
optimizer=torch.optim.AdamW(m.parameters(),lr=1e-3)

In [ ]:
batch_size=32
for steps in range(1000):
  xb, yb = get_batch("train")
  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

  print(steps, loss.item())

0 5.674291610717773
1 5.740190029144287
2 5.470076560974121
3 5.652226448059082
4 5.394737720489502
5 5.413332939147949
6 5.217104434967041
7 5.417500019073486
8 5.688005447387695
9 5.544562339782715
10 5.549103736877441
11 5.258592128753662
12 5.684421539306641
13 5.76786994934082
14 5.516416549682617
15 5.361427307128906
16 5.394472122192383
17 5.352010250091553
18 5.671931266784668
19 5.463718891143799
20 5.4550981521606445
21 5.786611557006836
22 5.469297409057617
23 5.600269794464111
24 5.3040266036987305
25 5.352242946624756
26 5.742997646331787
27 5.588135719299316
28 5.271021366119385
29 5.507146835327148
30 5.402458667755127
31 5.616122722625732
32 5.4625420570373535
33 5.257297992706299
34 5.391138076782227
35 5.54447078704834
36 5.63749361038208
37 5.474563121795654
38 5.591801166534424
39 5.916731357574463
40 5.349478721618652
41 5.484185218811035
42 5.389486312866211
43 5.593204021453857
44 5.397244453430176
45 5.550938129425049
46 5.611836910247803
47 5.271862983703613
48

In [ ]:
eval_iter=32

@torch.no_grad()
def estimate_loss():
  out={}
  model.eval()
  for split in ["train", "val"]:
    losses=torch.zeros(eval_iter)
    for k in range(eval_iter):
      X, Y = get_batch(split)
      logits, loss=model(X,Y)
      losses[k]=loss.item()
    out[split]=losses.mean()
  model.train()
  return out




In [ ]:
estimate_loss()

{'train': tensor(5.4921), 'val': tensor(6.0317)}

In [ ]:
for _ in range(30):
  myen=encode("白")
  mylen=len(myen)
  myword=torch.tensor(myen,dtype=torch.long, device=device)
  myword=torch.reshape(myword, (1,-1))
  mysen=decode(m.generate(myword, max_new_tokens=10-mylen)[0].tolist())
  print(mysen[:5]+"，"+mysen[5:]+"。")

白鼻如迎客，青壁补相途。
白日青毛里，沧浪碧云雷。
白刃红惆冒，黄河碧云深。
白马势难蜕，空门一幻间。
白皙非屈尊，长贫唯共求。
白刃风四灯，青霞月满渚。
白生淮桂暮，早晚值空山。
白阁临红袖，青山向夕阴。
白衫生麑马，黄金逆浪痕。
白露沾红粉，青霞与汍盘。
白首尝为客，青山梦已侵。
白发欣无锦，甘构共几回。
白水雁将古，春天不照低。
白帙新官路，黄红旧别卮。
白竿不可见，早晚无常营。
白刃翻青紫，丹云布古山。
白浆驾轻网，红绡想群蔽。
白云归客去，朱障望乡关。
白醪生欢曲，沧溟入破莲。
白阁万里行，机城雪岭禽。
白露贞无主，红霞半作蹊。
白驹穿篱燕，黄鸟满僧题。
白发至无气，雕文德益烦。
白衣粗身去，黄干难愿知。
白马少留画，孤戈谁意空。
白沟通欲略，黄禽鸟争飞。
白简烟霞低，青石空上铜。
白刃当街涩，朱旗千上禽。
白云行客久，黄里坐悠哉。
白石山阴气，青霞碧高城。


In [ ]:
torch.save(model.state_dict(), "model_gptang_v07.pth")

In [ ]:
# 加载保存的参数c
model = BigramLanguageModel()
m = model.to(device)
# 加载已保存的参数
m.load_state_dict(torch.load("model_gptang_v07.pth", weights_only=True))

<All keys matched successfully>