In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/tang
!ls -l

/content/drive/MyDrive/tang
total 268902
-rw------- 1 root root   120292 Jul 17 07:24 gptang_v01_Base.ipynb
-rw------- 1 root root   120267 Jul  2 06:16 gptang_v02_SingleHead.ipynb
-rw------- 1 root root   120819 Jul  2 05:58 gptang_v03_MultiHead.ipynb
-rw------- 1 root root   121283 Jul  2 05:42 gptang_v04_FeedForward.ipynb
-rw------- 1 root root   101263 Jul  2 04:01 gptang_v05_Block.ipynb
-rw------- 1 root root   121962 Jul  2 03:41 gptang_v06_FeedForwardOpt.ipynb
-rw------- 1 root root   122414 Jul  2 03:20 gptang_v07_LayerNorm.ipynb
-rw------- 1 root root   122040 Jul  2 08:05 gptang_v07_LayerNorm_rev.ipynb
-rw------- 1 root root   122867 Jul  2 02:49 gptang_v08_Full.ipynb
-rw------- 1 root root   124118 Jul  3 07:32 gptang_v08_Full_rev.ipynb
-rw------- 1 root root 14063576 Jul  2 06:29 model_gptang_v01.pth
-rw------- 1 root root 14851564 Jul  2 06:09 model_gptang_v02.pth
-rw------- 1 root root 14856498 Jul  2 05:55 model_gptang_v03.pth
-rw------- 1 root root 15120318 Jul  2 05:39

In [1]:
text=""
with open("tang_clean.txt", "r") as f:
   tmp_text = f.read()
   text = text + tmp_text
f.close()

chars = sorted(list(set(text)))
print(len(chars))
print("".join(chars))

6848
□一丁七万丈三上下不与丐丑专且丕世丘丙业丛东丝丞两严丧个丫中丰丱串丳临丸丹为主丽举乂乃久么义之乌乍乎乏乐乔乖乘乙九乞也习乡书买乱乳乾了予争事二于亏云互五井亘亚些亟亡亢交亥亦产亨亩享京亭亮亲亳亵亸亹人亿什仁仄仅仆仇今介仍从仑仓仔仕他仗付仙仝仞仡代令以仪仰仲仳价任仿企伉伊伋伍伎伏伐休众优会伛伞伟传伤伥伦伧伪伫伯估伴伶伸伺似伽但佉位低住佐佑体何佗余佚佛作佝佞你佣佥佩佪佯佳佶佺佾使侁侃侄侈例侍侏侑侔侗侘供依侠侣侥侧侨侪侬侮侯侵侹便促俄俊俋俎俗俘俚俛俜保俞俟信俣俦俨俩俪俫俭修俯俱俳俶俸俾倅倍倏倒倔倕倖倘候倚倜借倡倥倦倨倩倪倬倭倰债值倾偃假偈偎偏偓偕停健偪偬偲偶偷偻偾偿傀傅傍傥储傩催傭傲傺僁僇僎像僖僚僜僦僧僬僭僮僰僴僵僻僾儆儋儒儓儗儡儭儽儿兀允元兄充兆先光克免兑兔兕兖党兜兟兢入全八公六兮兰共关兴兵其具典兹养兼兽冀冁内冈冉册再冏冒冕冗写军农冠冢冤冥冬冯冰冱冲决况冶冷冻冽净凄准凉凊凋凌减凑凘凚凛凝几凡凤凫凭凯凰凶凸凹出击函凿刀刁刃分切刈刊刍刎刑划刓刖列刘则刚创刜初删判利别刬刮到刲刳制刷券刹刺刻刿剂剃剉削剌前剑剔剖剜剞剡剥剧剩剪副割剸剽剿劂劈劖劘劚力劝办功加务劣动助努劫劬劭励劲劳劻劼劾势勃勇勉勋勍勒勖勘募勤勩勷勺勾勿匀匄包匆匈匌匍匏匐匕化北匙匝匠匡匣匦匪匮匹区医匼匿十千升午卉半华协卑卒卓单卖南博卜卞占卢卤卦卧卨卫卮卯印危即却卵卷卸卺卼卿厄厅历厉压厌厓厕厖厘厚厝原厢厥厦厨厩厮去县参叆叇又叉及友双反发叔取受变叙叛叟叠口古句叨叩只叫召叮可台叱史右叵叶号司叹吁吃各合吉吊同名后吏吐向吒吓吕君吝吞吟吠否含听吭吮启吰吴吷吸吹吺吻吼吾呀呃呆呈告呐呕呗员呙呜呦周呱味呴呵呶呷呻呼命咀咂咄咆咋和咍咎咏咒咙咚咛咡咢咤咥咨咩咫咬咳咷咸咻咽咿哀品哂哄哆哇哈哉响哑哓哕哗哙哜哢哤哥哦哭哮哲哳哺哽唁唅唇唏唐唝唠唤唧售唯唱唳唶唼唽唾啀啁啄啅商啐啑啖啜啧啬啭啮啴啸啻啼啾喁喂喃善喈喉喋喍喎喑喓喔喘喙喜喝喟喢喣喧喷喻喽嗄嗅嗈嗒嗔嗗嗛嗜嗟嗢嗣嗤嗥嗫嗷嗽嗾嘈嘉嘐嘒嘕嘘嘤嘬嘱嘲嘴嘶嘹嘻嘿噀噅噆噇噌噎噏噞噢噣噤器噩噪噫噬噭噰噱嚄嚅嚏嚗嚘嚚嚣嚬嚭嚱嚼囊囐囗囚四回因团园困围囷囹固国图囿圃圄圆圈圉圜圞土圠圣在圭圮圯地圹场圻圿址坂均坊坌坎坏坐坑块坚坛坞坟坠坡坤坦坩坫坯坰坱坲坳坷坻坼垂垄垆型垌垒垓垛垞垠垡垢垣垤垦垩垫垲埂埃埆埇埋城埏埒埘埙埞域埤埭埳埴培基埽堂堄堆堇堌堑堕堙堛堞堠堡堤堪堮堰堵塉塌塍塔塘塞塠填塸塿墀墁境墅墉墍墐墓墙墝增墟

In [2]:
vocab_size = len(chars)
# 直接给编码映射关系
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
# 建立编码和解码函数
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: "".join([itos[i] for i in l])

In [3]:
encode("我是你好一二三四五六七八九十")

[1852, 2255, 177, 1065, 1, 70, 6, 859, 75, 340, 3, 338, 56, 532]

In [4]:
decode([1852, 2255, 177, 1065, 1, 70, 6, 859, 75, 340, 3, 338, 56, 532])

'我是你好一二三四五六七八九十'

In [7]:
import torch
#device="cuda" if torch.cuda.is_available() else "cpu"
device="cpu"
if torch.cuda.is_available():
    device="cuda"
if torch.backends.mps.is_available():
    device="mps"
print(device)

mps


In [7]:
import torch
data=torch.tensor(encode(text),dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])


torch.Size([1449490]) torch.int64
tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011, 3655, 1296, 4317, 2727,
         533, 1266, 5557, 3910, 1231, 3651, 6257, 6458, 5773, 4976, 5841, 2035,
        2774, 6420, 5267, 5777,  389, 5013,   73, 2219, 6233, 1294, 6178, 6408,
        3217,  406, 4317, 3578, 1338, 1532, 4400, 2355,  477, 1363, 2172, 4490,
        6508, 5725, 3409,  523,  651, 6838,  870, 5985, 4320, 1925,  398, 4103,
        6353, 4349, 2193,  108, 4316, 4364, 1458, 4643, 5768,  563, 1264, 2698,
          42, 2988, 3560, 2681, 2493, 5267,  904,  349, 3936, 2699,  406, 5359,
        2404,  272, 4638, 2673, 2700, 1234, 6264, 1556,  365, 2240, 2331, 6524,
        6495, 3579, 2904, 3548, 1752, 6252, 4875, 5013, 1566,  768, 3394, 1743,
        1677, 4097, 6161, 5529, 5371, 1026, 4420,   71,  350,   42, 1640,  255,
        6691, 4044,   34,   51, 6460, 3722,  648, 2672, 4706, 4685, 1677, 4090,
        6360, 2352, 1566, 2992, 2691,  395, 3650, 6269, 1591,  398, 4500, 2378,
      

In [8]:
n=(int)(len(data)*0.09)*10
train_data=data[0:n]
val_data=data[n:]
print(len(train_data), len(val_data))

1304540 144950


In [9]:
block_size=9
train_data[:block_size+1]

tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011, 3655, 1296])

In [10]:
x=train_data[:block_size]
y=train_data[1:block_size+1]
for t in range(block_size):
  context=x[:t+1]
  target=y[t]
  print(f"when input {context} then answer is {target}")

when input tensor([3926]) then answer is 1424
when input tensor([3926, 1424]) then answer is 6253
when input tensor([3926, 1424, 6253]) then answer is 1462
when input tensor([3926, 1424, 6253, 1462]) then answer is 1206
when input tensor([3926, 1424, 6253, 1462, 1206]) then answer is 408
when input tensor([3926, 1424, 6253, 1462, 1206,  408]) then answer is 5451
when input tensor([3926, 1424, 6253, 1462, 1206,  408, 5451]) then answer is 1011
when input tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011]) then answer is 3655
when input tensor([3926, 1424, 6253, 1462, 1206,  408, 5451, 1011, 3655]) then answer is 1296


In [11]:
torch.manual_seed(1337)
batch_size=32
block_size=9

def get_batch(split):
  data=train_data if split=="train" else val_data
  #find the start position
  ix=torch.randint((int)(len(data)/10-1),(batch_size,))*10
  #for t in ix:
    #print(t)
  x=torch.stack([data[i:i+block_size] for i in ix])
  y=torch.stack([data[i+1:i+block_size+1] for i in ix])
  x=x.to(device)
  y=y.to(device)
  return x, y


In [12]:
xb,yb=get_batch("train")
print("Inputs:")
print(xb.shape)
print(xb)
print("Outputs:")
print(yb.shape)
print(yb)
print("--------------")

for b in range(batch_size):
  for t in range(block_size):
    context=xb[b, :t+1]
    target=yb[b,t]
    print(f"when input is {context.tolist()}, the target is {target}")

Inputs:
torch.Size([32, 9])
tensor([[2195, 5368, 3676, 5835, 5602, 2992, 6360,  159, 2167],
        [ 213,  213, 1652, 5835, 5602,  859, 2143,    9, 1471],
        [2219, 2305, 6776,   73,  629, 1491, 2985, 3650, 6544],
        [2658, 3307, 6420, 4705,  336, 1532, 1868, 3141, 2767],
        [3975, 4292, 2490, 4705,  903,    9, 5266, 3926, 2228],
        [5985, 4320,  324, 3556, 5835, 3409, 2430,  560, 5412],
        [2340, 5602, 2711, 2346, 3972, 1974, 2342,  106, 1436],
        [1314, 2829, 5557, 3692,  451, 3732, 3712, 2702, 5602],
        [1798,  641,  919, 5978, 2094,    9,  187, 4875, 6408],
        [5788, 2842, 3578, 3781, 4003, 2712, 6267,  598, 2559],
        [ 660,  641, 2196, 1646, 5752,  413, 6159, 5519, 1029],
        [ 612, 1509, 1235, 2523, 5980, 5368,  345, 1305, 2786],
        [1499, 1524, 1673, 6269,  383, 2985, 1299,  784, 3193],
        [ 117, 1272, 5556, 1236, 3409, 4738, 6408,  389,  859],
        [2774, 3441, 3560, 5835,  675, 2785, 3505, 5766, 3709],
        [ 12

In [13]:
xb,yb=get_batch("val")
print("Inputs:")
print(xb.shape)
print(xb)
print("Outputs:")
print(yb.shape)
print(yb)
print("--------------")

for b in range(batch_size):
  for t in range(block_size):
    context=xb[b, :t+1]
    target=yb[b,t]
    print(f"when input is {context.tolist()}, the target is {target}")

Inputs:
torch.Size([32, 9])
tensor([[6269, 4557, 6710, 6113, 5980, 3463, 2468,  398, 2589],
        [5902, 4351, 1630,  159, 2767, 2150,  123, 6037,   37],
        [3239, 5400, 4013, 1066,  169, 5398,  209, 5266, 5981],
        [  73, 6277,  647,   36, 2284, 2496, 6773, 5265, 4283],
        [3910, 1707,  429, 5814, 4685, 5494, 1296,  612,  784],
        [3459, 2378, 6152,  439,  836,  128, 5165, 4543, 5773],
        [1020, 3923, 2196,  390, 6421, 3918, 2219, 2323, 6152],
        [  63, 1359, 2785,    7, 4681, 4426, 1276,  594, 3918],
        [1268, 5927,  106, 2341, 5770, 2217, 6313,  406,   16],
        [3544, 1037, 2332, 6753, 5789, 3545, 1291, 4879, 2219],
        [1194, 3993, 3214, 1597, 1624,  169,   69, 6194,  644],
        [5927,   91, 3560,  587, 5789,  653,  892, 5326,  821],
        [2250, 6267, 2217, 6560,    8, 4705, 2408, 2332, 3778],
        [   1,   40, 2904, 6294, 2888,  533, 1491,  882,  214],
        [1024, 4730, 1489, 4987, 2172,   29, 2332, 2300, 2930],
        [149

In [14]:
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)
n_embed=256

class BigramLanguageModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.token_embedding_table=nn.Embedding(vocab_size, n_embed)
    self.postion_embedding_table=nn.Embedding(block_size,n_embed)
    self.lm_head=nn.Linear(n_embed,vocab_size)

  def forward(self, idx, targets=None):
    B,T=idx.shape
    tok_emb=self.token_embedding_table(idx)
    pos_emd=self.postion_embedding_table(torch.arange(T,device=device))
    x=tok_emb+pos_emd
    logits=self.lm_head(x)
    if targets is None:
      loss=None
    else:
      B,T,C=logits.shape
      logits=logits.view(B*T,C)
      targets=targets.view(B*T)
      loss=F.cross_entropy(logits, targets)
      #print(loss)
    return logits, loss

  def generate(self, idx, max_new_tokens):
    for _ in range(max_new_tokens):
      logits,loss=self(idx)
      logits=logits[:,-1,:]
      probs=F.softmax(logits, dim=-1)
      idx_next=torch.multinomial(probs, num_samples=1)
      idx=torch.cat((idx, idx_next),dim=1)
    return idx

model=BigramLanguageModel()
m=model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
logits, loss =m(xb,yb)
print(logits.shape)
print(loss)
print(decode(m.generate(torch.ones((1,1),dtype=torch.long,device=device), max_new_tokens=9)[0].tolist()))

3.515328 M parameters
torch.Size([288, 6848])
tensor(9.1768, grad_fn=<NllLossBackward0>)
一喙湟腽艰臂辂雭摩鹥


In [15]:
optimizer=torch.optim.AdamW(m.parameters(),lr=1e-2)

In [16]:
batch_size=32
for steps in range(1000):
  xb, yb = get_batch("train")
  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

  print(steps, loss.item())

0 9.162845611572266
1 8.829261779785156
2 8.581714630126953
3 8.667675018310547
4 8.657292366027832
5 8.653221130371094
6 8.805754661560059
7 8.876628875732422
8 8.91031265258789
9 8.564027786254883
10 8.99453353881836
11 8.834200859069824
12 8.755395889282227
13 8.945174217224121
14 8.422979354858398
15 8.591607093811035
16 8.193782806396484
17 8.854227066040039
18 8.323631286621094
19 8.475937843322754
20 8.671374320983887
21 8.721179962158203
22 8.209904670715332
23 8.24844741821289
24 8.40798568725586
25 8.060538291931152
26 8.50085163116455
27 8.186023712158203
28 8.078900337219238
29 8.66157341003418
30 8.191702842712402
31 7.834822654724121
32 8.247607231140137
33 8.313154220581055
34 8.20261287689209
35 8.225521087646484
36 8.688905715942383
37 8.554548263549805
38 8.23691177368164
39 8.135603904724121
40 8.19123363494873
41 8.53585433959961
42 8.248222351074219
43 8.012261390686035
44 7.99774169921875
45 7.725541114807129
46 8.015074729919434
47 7.888442039489746
48 8.24531650

In [ ]:
eval_iter=32

@torch.no_grad()
def estimate_loss():
  out={}
  model.eval()
  for split in ["train", "val"]:
    losses=torch.zeros(eval_iter)
    for k in range(eval_iter):
      X, Y = get_batch(split)
      logits, loss=model(X,Y)
      losses[k]=loss.item()
    out[split]=losses.mean()
  model.train()
  return out




In [17]:
estimate_loss()

NameError: name 'estimate_loss' is not defined

In [ ]:
for _ in range(20):
  myen=encode("白")
  mylen=len(myen)
  myword=torch.tensor(myen,dtype=torch.long, device=device)
  myword=torch.reshape(myword, (1,-1))
  mysen=decode(m.generate(myword, max_new_tokens=10-mylen)[0].tolist())
  print(mysen[:5]+"，"+mysen[5:]+"。")

白色光箭尽，云裘委曲溪。
白马关稷盖，不称作云埋。
白气仍临扉，隐夜清净华。
白徒自不弃，丹霄堪散氲。
白轩烟水晚，龄等迁觐省。
白葳蕤长剑，犹胜茂亭凤。
白鹤静枯巷，是酒与警声。
白云澹桂折，江雨晦吟人。
白雪惊春小，鼻我千金钿。
白日九绛苑，上国楚江空。
白马转经地，罔有时斗声。
白发忧势曲，坐病榜海躇。
白简神明沼，独抱妇人垢。
白头领导之，巡栗节前程。
白云为我适，忘忧满年杯。
白云出来彩，翠沓对日光。
白日滑仪卫，海叟已自还。
白雪明月满，地不胜无是。
白楼今长急，征帆耿宿心。
白马尘海底，还欲速肥初。


In [ ]:
torch.save(model.state_dict(), "model_gptang_v01.pth")

In [ ]:
# 加载保存的参数c
model = BigramLanguageModel()
m = model.to(device)
# 加载已保存的参数
m.load_state_dict(torch.load("model_gptang_v01.pth", weights_only=True))